// Local preview data for the OpenClaw Cooperative Cockpit MVP.

/*
  This file defines the data used by the front‑end prototype. All values
  are fixed and do not come from any external service. You can adjust
  coordinates or labels here to reposition nodes on the Workbench.
*/

window.mockData = {
  workspace: {
    id: 'workspace-static-mvp',
    name: 'OpenClaw Local Workspace',
    mode: 'Local preview',
    constraints: [
      'No backend, API, auth, database, deployment, or external connectors',
      'No runtime workflow execution or real agent orchestration',
      'No repo writes from the local workspace',
    ],
  },

  project: {
    id: 'project-cooperative-cockpit-static-mvp',
    name: 'OpenClaw Cooperative Cockpit',
    artifactId: 'COCKPIT-MVP-014',
    summary: 'Governed context, spec, review, evidence, decision, and handoff readiness workspace.',
    currentStage: 'Cockpit readiness alignment',
    status: 'draft',
  },

  contextNodes: [
    {
      id: 'node-1',
      label: 'User Input / Concept Intake',
      type: 'intake',
      status: 'validated',
      description: 'Captures the human-provided goal, constraints and stop conditions before any drafting begins.',
      x: 20,
      y: 24,
      links: ['node-2', 'objective'],
    },
    {
      id: 'node-2',
      label: 'Context Selector',
      type: 'context',
      status: 'validated',
      description: 'Chooses safe source material for the spec while keeping protected surfaces excluded.',
      x: 50,
      y: 20,
      links: ['node-3', 'source-context'],
    },
    {
      id: 'node-3',
      label: 'Spec Builder',
      type: 'spec',
      status: 'draft',
      description: 'Turns the selected context into controlled fields, acceptance criteria and handoff gates.',
      x: 80,
      y: 32,
      links: ['node-4', 'spec-draft-primary'],
    },
    {
      id: 'node-6',
      label: 'Decision',
      type: 'decision',
      status: 'needs-lock',
      description: 'Surfaces unresolved approval points that must be locked before a handoff is available.',
      x: 20,
      y: 80,
      links: ['D-005', 'handoff-preview'],
    },
    {
      id: 'node-8',
      label: 'Handoff Packet',
      type: 'handoff',
      status: 'blocked',
      description: 'Prepares a handoff preview only after specs, decisions and evidence are ready.',
      x: 80,
      y: 82,
      links: ['work-packet-primary-workflow', 'handoff-packet-primary-workflow'],
    },
  ],

  selectedContext: {
    includedIds: ['node-1', 'node-2'],
    protectedExclusions: [
      { id: 'runtime-state', label: 'Runtime state', status: 'excluded' },
      { id: 'secrets', label: 'Secrets', status: 'excluded' },
      { id: 'repo-write', label: 'Repo write authority', status: 'excluded' },
    ],
  },

  specTemplates: [
    {
      id: 'template-product-spec',
      name: 'Product Spec',
      description: 'Structures objective, protected surfaces, acceptance criteria, and validation method.',
      fieldIds: ['objective', 'layout-regions', 'interaction-states', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    },
    {
      id: 'template-review-brief',
      name: 'Review Brief',
      description: 'Frames inspect-only review context and finding evidence expectations.',
      fieldIds: ['objective', 'interaction-states', 'protected-surfaces', 'validation-method'],
    },
    {
      id: 'template-codex-handoff',
      name: 'Codex Handoff',
    description: 'Collects bounded workspace scope, protected boundaries, acceptance criteria, and readiness checks.',
      fieldIds: ['objective', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    },
  ],

  specDraft: {
    id: 'spec-draft-primary',
    templateId: 'template-product-spec',
    status: 'draft',
    fieldIds: ['objective', 'layout-regions', 'interaction-states', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    readiness: 'blocked',
  },

  // Nodes displayed on the Workbench canvas. Coordinates are percentages
  // relative to the canvas container for quick placement. These are static
  // workflow operators; they do not call models, services or runtime tools.
  nodes: [
    {
      id: 'node-1',
      fieldIds: ['objective', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    },
  ],

  specDraft: {
    id: 'spec-draft-primary',
    templateId: 'template-product-spec',
    status: 'draft',
    fieldIds: ['objective', 'layout-regions', 'interaction-states', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    readiness: 'blocked',
  },

  nodes: [
    // ==================== LEVEL 1: PRODUCT REQUIREMENTS ====================
    {
      id: 'req-1',
      parentId: null,
      level: 'requirements',
      index: '01',
      label: 'Product Requirement',
      type: 'intake',
      typeLabel: 'Requirement',
      x: 30,
      y: 50,
      status: 'validated',
      family: 'context',
      familyLabel: 'Product Level',
      title: 'PR-1: Sandbox & Governance',
      subtitle: 'Ensures safe, inspect-only local browser boundaries.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 3,
      description: 'Requires all operations to run inspect-only without backend execution, API writeback, or secret mutation.',
      config: 'OpenClaw Sandbox Spec v1.0',
      model: 'Rule engine',
      inputs: ['Goal brief', 'Workspace constraints'],
      outputs: ['Safe context boundary'],
      guardrails: ['Secrets excluded', 'No filesystem writes', 'No backend side-effects'],
      trace: ['source: user brief', 'evidence: exclusion check'],
      requirements: ['Goal and stop conditions captured', 'Workspace scope and local-only constraint stated'],
      evidence: ['Goal template linked', 'Local-only constraint recorded'],
      review: ['No execution verbs required', 'Inspect-only context remains verified'],
      handoff: ['Feeds safe sandbox boundaries to downstream architecture maps'],
    },
    {
      id: 'req-2',
      parentId: null,
      level: 'requirements',
      index: '02',
      label: 'Product Requirement',
      type: 'trace',
      typeLabel: 'Requirement',
      x: 70,
      y: 50,
      status: 'draft',
      family: 'evidence',
      familyLabel: 'Product Level',
      title: 'PR-2: Spec & Traceability',
      subtitle: 'Binds goals to spec fields, decisions, and evidence.',
      readiness: 'draft',
      blockerCount: 3,
      evidenceCount: 1,
      description: 'Requires that all specification fields have verifiable trace links and locked Point-decisions before handoff unlocks.',
      config: 'Traceability Gating policy',
      model: 'Audit checker',
      inputs: ['Safe context boundary', 'Locked decisions'],
      outputs: ['Auditable handoff specification'],
      guardrails: ['Unresolved blockers prevent handoff', 'Missing trace links yield warnings'],
      trace: ['source: spec fields', 'evidence: trace map'],
      requirements: ['Each spec field linked to evidence', 'All blockers resolved or deferred'],
      evidence: ['Spec fields table', 'Decisions board'],
      review: ['Readiness checks hold gate', 'Deferred decisions hold readiness'],
      handoff: ['Enables locked handoff preview after validation checks clear'],
    },

    // ==================== LEVEL 2: ARCHITECTURE MAP ====================
    // Under req-1 (Sandbox & Governance)
    {
      id: 'arch-1',
      parentId: 'req-1',
      level: 'architecture',
      index: '03',
      label: 'Architecture Module',
      type: 'context',
      typeLabel: 'Architecture',
      x: 35,
      y: 50,
      status: 'validated',
      family: 'context',
      familyLabel: 'Architecture Level',
      title: 'Governed UI Canvas Engine',
      subtitle: 'Coordinates spatial layouts and sandbox navigation.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 2,
      description: 'Manages the sandbox layout, dynamic node positioning, and reactive inspector panels without server side-effects.',
      config: 'Vanilla JS Rendering Pipeline',
      model: 'SPA Router',
      inputs: ['Workspace constraints', 'Nodes database'],
      outputs: ['Rendered SPA views'],
      guardrails: ['Flicker-free selective redraws', 'No external network fetches'],
      trace: ['component: app.js', 'evidence: DOM nodes'],
      requirements: ['Fluid rendering of S-curve bezier connections', 'No global re-renders on selection'],
      evidence: ['Flicker-free selection implemented', 'CSS transform animations validated'],
      review: ['SPA router verified', 'Local view state only'],
      handoff: ['Powers the visual display of components and phases'],
    },
    {
      id: 'arch-2',
      parentId: 'req-1',
      level: 'architecture',
      index: '04',
      label: 'Architecture Module',
      type: 'handoff',
      typeLabel: 'Architecture',
      x: 65,
      y: 50,
      status: 'draft',
      family: 'handoff',
      familyLabel: 'Architecture Level',
      title: 'Handoff Gating Router',
      subtitle: 'Evaluates readiness criteria and blocks packet exports.',
      readiness: 'draft',
      blockerCount: 2,
      evidenceCount: 1,
      description: 'Validates checklist markers, checks advisory review findings, and locks handoff packaging until safety gates clear.',
      config: 'Gating Specification Model',
      model: 'Checklist validator',
      inputs: ['Advisory findings', 'Spec draft status'],
      outputs: ['Unlocked handoff action state'],
      guardrails: ['Handoff remains disabled until blockers = 0', 'Inspect-only notice on preview'],
      trace: ['component: state.js', 'evidence: handoffReady flag'],
      requirements: ['Gating locks checked locally', 'Safe handoff button feedback'],
      evidence: ['Disabled button visual state checked'],
      review: ['Manual local preview smoke check verified'],
      handoff: ['Unlocks the final export manifest preview'],
    },
    // Under req-2 (Spec & Traceability)
    {
      id: 'arch-3',
      parentId: 'req-2',
      level: 'architecture',
      index: '05',
      label: 'Architecture Module',
      type: 'trace',
      typeLabel: 'Architecture',
      x: 50,
      y: 50,
      status: 'needs-sync',
      family: 'evidence',
      familyLabel: 'Architecture Level',
      title: 'Traceability & Evidence Store',
      subtitle: 'Audits context selector, specs, and verification links.',
      readiness: 'needs-evidence',
      blockerCount: 2,
      evidenceCount: 2,
      description: 'Manages the index of active trace links, binds spec fields to evidence items, and generates auditable maps.',
      config: 'Trace Link Registry',
      model: 'Graph database mimic',
      inputs: ['Selected Context', 'Spec draft fields', 'Evidence list'],
      outputs: ['Traceability matrix'],
      guardrails: ['Detect unlinked spec fields', 'Enforce exclusion rules'],
      trace: ['component: mockData.js', 'evidence: traceLinks array'],
      requirements: ['Each spec field has valid trace link', 'Exclusion checklist sealed'],
      evidence: ['Traceability table items', 'Protected exclusions sealed'],
      review: ['Trace review: check missing links'],
      handoff: ['Feeds auditable traces into the handoff manifest'],
    },

    // ==================== LEVEL 3: SOFTWARE COMPONENTS ====================
    // Under arch-1 (Canvas Engine)
    {
      id: 'comp-1',
      parentId: 'arch-1',
      level: 'component',
      index: '06',
      label: 'Software Component',
      type: 'context',
      typeLabel: 'Component',
      x: 30,
      y: 50,
      status: 'validated',
      family: 'context',
      familyLabel: 'Component Level',
      title: 'Interactive Canvas Flow',
      subtitle: 'Renders absolute cards and curved SVG connections.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 1,
      description: 'Visual flow container drawing bezier lines between cards using absolute grid percentages.',
      config: 'SVG Canvas rendering',
      model: 'Pure CSS + Svg',
      inputs: ['Active level nodes', 'Active edges'],
      outputs: ['Visual flowchart overlay'],
      guardrails: ['No overlapping lines', 'Dynamic resizing handlers'],
      trace: ['source: components.css', 'evidence: S-curves'],
      requirements: ['Resize listener bound', 'Double-click drill-down hooks active'],
      evidence: ['Bezier edge coordinates calculated dynamically'],
      review: ['S-curves flow review: validated'],
      handoff: ['Provides visual framework for execution phases'],
    },
    {
      id: 'comp-2',
      parentId: 'arch-1',
      level: 'component',
      index: '07',
      label: 'Software Component',
      type: 'intake',
      typeLabel: 'Component',
      x: 70,
      y: 50,
      status: 'validated',
      family: 'context',
      familyLabel: 'Component Level',
      title: 'Inspector & Sidebar Rails',
      subtitle: 'Manages sliding panels and context checklists.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 1,
      description: 'Sidebar containing the locked object palette and context basket, paired with the sliding right-hand inspector.',
      config: 'Sliding panel component',
      model: 'Reactive DOM drawers',
      inputs: ['Selected node ID', 'Context items array'],
      outputs: ['Details panel view', 'Basket item chips'],
      guardrails: ['Exclusions cannot be dragged to basket', 'Flicker-free inspector tab switching'],
      trace: ['source: app.js L810', 'evidence: inspector drawer'],
      requirements: ['Tabs render on active selected node details', 'Local safety notice stays visible'],
      evidence: ['Inspector DOM drawer verified'],
      review: ['No side-effects on inspector render: pass'],
      handoff: ['Renders specification details for active component views'],
    },
    // Under arch-2 (Handoff Router)
    {
      id: 'comp-3',
      parentId: 'arch-2',
      level: 'component',
      index: '08',
      label: 'Software Component',
      type: 'spec',
      typeLabel: 'Component',
      x: 30,
      y: 50,
      status: 'draft',
      family: 'spec',
      familyLabel: 'Component Level',
      title: 'Readiness Gating Checker',
      subtitle: 'Aggregates blockers, review findings, and checklist.',
      readiness: 'draft',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Calculates active blocking items by analyzing specification templates, unresolved D-005 lock state, and evidence warnings.',
      config: 'Aggregator logic spec',
      model: 'Checklist compiler',
      inputs: ['Spec draft status', 'Findings list', 'Decisions list'],
      outputs: ['Aggregated blocker count', 'Readiness verdict'],
      guardrails: ['Fail-closed: any blocker keeps readiness blocked'],
      trace: ['source: app.js getReadinessSummary()', 'evidence: blockers array'],
      requirements: ['Correct blocker summation', 'Accurate state.js update'],
      evidence: ['Readiness sum verified locally'],
      review: ['Safety gate audit: locked'],
      handoff: ['Instructs the Packet Assembly on gating state'],
    },
    {
      id: 'comp-4',
      parentId: 'arch-2',
      level: 'component',
      index: '09',
      label: 'Software Component',
      type: 'handoff',
      typeLabel: 'Component',
      x: 70,
      y: 50,
      status: 'blocked',
      family: 'handoff',
      familyLabel: 'Component Level',
      title: 'Handoff Packet Assembly',
      subtitle: 'Prepares the governed handoff manifest draft.',
      readiness: 'blocked',
      blockerCount: 2,
      evidenceCount: 1,
      description: 'Builds a local handoff manifest with allowed paths, exclusions, acceptance criteria, and validation history.',
      config: 'Manifest compiler template',
      model: 'JSON manifest schema',
      inputs: ['Spec fields', 'Trace links', 'Readiness checker verdict'],
      outputs: ['Draft handoff manifest JSON preview'],
      guardrails: ['Read-only mock preview', 'Zero filesystem exports permitted'],
      trace: ['source: mockData.js handoffPacketPreview', 'evidence: handoff page'],
      requirements: ['Renders complete JSON draft details', 'Gated button functions correctly'],
      evidence: ['Manifest preview populated'],
      review: ['Compliance scan: pass'],
      handoff: ['Renders final output page details'],
    },
    // Under arch-3 (Trace Store)
    {
      id: 'comp-5',
      parentId: 'arch-3',
      level: 'component',
      index: '10',
      label: 'Software Component',
      type: 'trace',
      typeLabel: 'Component',
      x: 30,
      y: 50,
      status: 'needs-sync',
      family: 'evidence',
      familyLabel: 'Component Level',
      title: 'Trace Link Database',
      subtitle: 'Manages source-target schema structures.',
      readiness: 'needs-evidence',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Maintains connections between active nodes and specification variables to guarantee auditable context.',
      config: 'Schema trace map',
      model: 'Array mapping store',
      inputs: ['Context nodes list', 'Spec draft fields'],
      outputs: ['Active connections array'],
      guardrails: ['Alert on detached spec properties', 'Exclusion isolation compliance'],
      trace: ['source: mockData.js traceLinks', 'evidence: trace page'],
      requirements: ['Accurate connection map', 'Sealed exclusion parameters'],
      evidence: ['Exclusions isolation confirmed'],
      review: ['Database structure scan: pass'],
      handoff: ['Feeds verification engines with active traces'],
    },
    {
      id: 'comp-6',
      parentId: 'arch-3',
      level: 'component',
      index: '11',
      label: 'Software Component',
      type: 'preview',
      typeLabel: 'Component',
      x: 70,
      y: 50,
      status: 'needs-sync',
      family: 'evidence',
      familyLabel: 'Component Level',
      title: 'Evidence Linking Handler',
      subtitle: 'Attaches preview frames and validation results.',
      readiness: 'needs-evidence',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Records and compiles manual browser checks, automated validators, and mock previews into visual evidence cards.',
      config: 'Evidence compiler',
      model: 'Evidence schema',
      inputs: ['Validation results array', 'Preview snapshots'],
      outputs: ['Linked evidence logs'],
      guardrails: ['Warnings displayed for incomplete checks', 'No external assets loaded'],
      trace: ['source: mockData.js evidenceItems', 'evidence: trace page'],
      requirements: ['Dynamic verification state update', 'Notice banners visible'],
      evidence: ['Warning icons render correctly'],
      review: ['Verify safety boundaries: pass'],
      handoff: ['Supplies verification matrices to Handoff Assembly'],
    },

    // ==================== LEVEL 4: EXECUTION PHASES ====================
    // Under comp-1 (Interactive Canvas Flow)
    {
      id: 'phase-1',
      parentId: 'comp-1',
      level: 'phase',
      index: '12',
      label: 'Execution Phase',
      type: 'intake',
      typeLabel: 'Phase',
      x: 50,
      y: 50,
      status: 'validated',
      family: 'context',
      familyLabel: 'Phase Level',
      title: 'Intake & Context Phase',
      subtitle: 'Establishes concept scopes and seals exclusions.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 2,
      description: 'Prepares the safety boundaries by capturing the goal brief and locking protected exclusions prior to specification drafting.',
      config: 'Concept intake spec',
      model: 'Exclusion filter',
      inputs: ['Goal brief', 'Exclusions list'],
      outputs: ['Safe context workspace'],
      guardrails: ['Exclusions completely isolated', 'Goalbrief stored in browser localState'],
      trace: ['stage: source-context-stage', 'evidence: intake nodes'],
      requirements: ['Goal captured and isolation locked', 'Excluded list visible'],
      evidence: ['Exclusions isolation test: passed'],
      review: ['Concept verification review: approved'],
      handoff: ['Passes verified safety context boundaries to the spec phase'],
    },
    // Under comp-3 (Readiness Gating Checker)
    {
      id: 'phase-2',
      parentId: 'comp-3',
      level: 'phase',
      index: '13',
      label: 'Execution Phase',
      type: 'spec',
      typeLabel: 'Phase',
      x: 30,
      y: 50,
      status: 'draft',
      family: 'spec',
      familyLabel: 'Phase Level',
      title: 'Specification Drafting Phase',
      subtitle: 'Assembles controlled build spec requirements.',
      readiness: 'draft',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Structures the safe context into formatted spec fields, template checklists, and handoff criteria.',
      config: 'Spec template selection',
      model: 'Draft compiler',
      inputs: ['Safe context workspace'],
      outputs: ['Drafted specification fields'],
      guardrails: ['Draft fields require human locks', 'Unsafe execution tags unavailable'],
      trace: ['stage: governed-spec', 'evidence: spec draft'],
      requirements: ['Required template fields populated', 'Verification indicators attached'],
      evidence: ['Spec draft structure compiled in localState'],
      review: ['Spec structure review: draft status'],
      handoff: ['Passes draft spec structure to advisory checkers'],
    },
    {
      id: 'phase-3',
      parentId: 'comp-3',
      level: 'phase',
      index: '14',
      label: 'Execution Phase',
      type: 'review',
      typeLabel: 'Phase',
      x: 70,
      y: 50,
      status: 'needs-lock',
      family: 'review',
      familyLabel: 'Phase Level',
      title: 'Advisory Verification Phase',
      subtitle: 'Aggregates safety checkers and locks gates.',
      readiness: 'needs-decision',
      blockerCount: 3,
      evidenceCount: 2,
      description: 'Triggers inspect-only verification checkers, logs findings, and locks required governance checkpoints.',
      config: 'Verification checklist',
      model: 'Review orchestrator',
      inputs: ['Drafted specification fields'],
      outputs: ['Verification logs', 'Locked decision records'],
      guardrails: ['Fail-closed on open blocker', 'Advisory reports inspect-only'],
      trace: ['stage: decision-evidence-gate', 'evidence: findings + decisions'],
      requirements: ['Advisory findings reviewed', 'Gating locks applied by Point'],
      evidence: ['Findings loaded', 'D-005 gate locked in mockState'],
      review: ['Verify safety gates: awaiting lock'],
      handoff: ['Passes verification matrices to packet assembly'],
    },
    // Under comp-4 (Handoff Assembly)
    {
      id: 'phase-4',
      parentId: 'comp-4',
      level: 'phase',
      index: '15',
      label: 'Execution Phase',
      type: 'handoff',
      typeLabel: 'Phase',
      x: 50,
      y: 50,
      status: 'blocked',
      family: 'handoff',
      familyLabel: 'Phase Level',
      title: 'Packet Assembly Phase',
      subtitle: 'Aggregates locked matrices and opens previews.',
      readiness: 'blocked',
      blockerCount: 2,
      evidenceCount: 1,
      description: 'Validates that all upstream phases are locked, compiles trace matrices, and renders the mock handoff package preview.',
      config: 'Handoff compiler',
      model: 'Mock manifest assembler',
      inputs: ['Locked verification matrices'],
      outputs: ['Draft handoff preview package'],
      guardrails: ['Button disabled until all gates locked', 'Zero filesystem exports'],
      trace: ['stage: handoff-preview', 'evidence: handoff package'],
      requirements: ['Checked handoff criteria resolved', 'All safety tags validated'],
      evidence: ['Manifest preview loaded'],
      review: ['Handoff safety scanner: pass'],
      handoff: ['Fulfills the local cockpit workspace alignment'],
    },

    // ==================== LEVEL 5: ACTIONABLE TASKS (Original 8 Nodes) ====================
    // Under phase-1 (Intake Phase)
    {
      id: 'node-1',
      parentId: 'phase-1',
      level: 'task',
      index: '01',
      label: 'User Input / Concept Intake',
      type: 'intake',
      typeLabel: 'Input',
      x: 20,
      y: 24,
      status: 'validated',
      family: 'context',
      familyLabel: 'Context Node',
      title: 'Goal Intake',
      subtitle: 'Frames the Work Packet before drafting.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 2,
      description: 'Captures the human-provided goal, constraints and stop conditions before any drafting begins.',
      config: 'Goal brief + workspace scope',
      model: 'Human-authored',
      inputs: ['Point brief', 'Goal template'],
      outputs: ['Scoped concept packet'],
      guardrails: ['No runtime mutation', 'No hidden external calls'],
      trace: ['source: goal brief', 'decision: local preview only'],
      requirements: ['Goal and stop conditions captured', 'Workspace scope and local-only constraint stated'],
      evidence: ['Goal template linked', 'Local-only constraint recorded'],
      review: ['No execution verbs required', 'Human-authored context remains inspect-only'],
      handoff: ['Feeds the scoped concept packet into the Work Packet'],
    },
    {
      id: 'node-2',
      parentId: 'phase-1',
      level: 'task',
      index: '02',
      label: 'Context Selector',
      type: 'context',
      typeLabel: 'Context',
      x: 50,
      y: 20,
      status: 'validated',
      family: 'context',
      familyLabel: 'Context Node',
      title: 'Safe Selected Context',
      subtitle: 'Separates usable context from protected exclusions.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 3,
      description: 'Chooses safe source material for the spec while keeping protected surfaces excluded.',
      config: 'Selected Context policy',
      model: 'Local selector',
      inputs: ['Scoped concept packet', 'Protected exclusions'],
      outputs: ['Included context set'],
      guardrails: ['Secrets excluded', 'Repo write authority excluded'],
      trace: ['source: selected context', 'evidence: exclusions list'],
      requirements: ['Protected exclusions remain sealed', 'Included context stays local to the browser'],
      evidence: ['Selected Context item list', 'Protected Exclusions list', 'Local browser state only'],
      review: ['Secrets and repo write authority remain excluded'],
      handoff: ['Included context becomes Handoff Packet source material only after gates pass'],
    },
    // Under phase-2 (Drafting Phase)
    {
      id: 'node-3',
      parentId: 'phase-2',
      level: 'task',
      index: '03',
      label: 'Spec Builder',
      type: 'spec',
      typeLabel: 'Draft',
      x: 80,
      y: 32,
      status: 'draft',
      family: 'spec',
      familyLabel: 'Work Packet',
      title: 'Spec Assembly',
      subtitle: 'Turns context into controlled artifact requirements.',
      readiness: 'draft',
      blockerCount: 3,
      evidenceCount: 2,
      description: 'Turns the selected context into controlled fields, acceptance criteria and handoff gates.',
      config: 'UI / UX Spec template',
      model: 'Draft suggestions',
      inputs: ['Included context set'],
      outputs: ['Draft build spec'],
      guardrails: ['Human locks required', 'Unsafe action labels unavailable'],
      trace: ['target: spec fields', 'decision: template set'],
      requirements: ['Required fields resolved', 'Human locks applied before handoff'],
      evidence: ['Spec fields table', 'Template decision record'],
      review: ['Missing fields hold readiness', 'Suggestions do not call AI services'],
      handoff: ['Locked Work Packet is required before preparing a Handoff Packet'],
    },
    // Under phase-3 (Verification Phase)
    {
      id: 'node-4',
      parentId: 'phase-3',
      level: 'task',
      index: '04',
      label: 'Review Agent',
      type: 'review',
      typeLabel: 'Review',
      x: 34,
      y: 56,
      status: 'needs-lock',
      family: 'review',
      familyLabel: 'Review Gate',
      title: 'Advisory Review',
      subtitle: 'Collects inspect-only review findings and readiness items.',
      readiness: 'review-blocked',
      blockerCount: 2,
      evidenceCount: 2,
      description: 'Provides inspect-only review findings and advisory notes without changing runtime or repository state.',
      config: 'Inspect-only checks',
      model: 'Local review set',
      inputs: ['Draft build spec', 'Included context set'],
      outputs: ['Advisory findings'],
      guardrails: ['No auto-fix', 'No repository writes'],
      trace: ['page: Review Runs', 'evidence: finding cards'],
      requirements: ['Findings are advisory only', 'High-risk ambiguities are visible before handoff'],
      evidence: ['Review Runs page', 'Finding cards'],
      review: ['Architecture Review: revise', 'Red Team Review: high-risk ambiguities'],
      handoff: ['Review items must be acknowledged locally before handoff can unlock'],
    },
    {
      id: 'node-5',
      parentId: 'phase-3',
      level: 'task',
      index: '05',
      label: 'Preview Renderer',
      type: 'preview',
      typeLabel: 'Preview',
      x: 65,
      y: 58,
      status: 'needs-sync',
      family: 'evidence',
      familyLabel: 'Evidence',
      title: 'Preview Evidence',
      subtitle: 'Shows local artifact coverage without rendering real output.',
      readiness: 'needs-evidence',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Shows artifact preview and coverage state without generating or executing code.',
      config: 'HTML viewer',
      model: 'Local renderer',
      inputs: ['Draft build spec', 'Advisory findings'],
      outputs: ['Preview state'],
      guardrails: ['No real generation', 'No external assets'],
      trace: ['page: UI / HTML Viewer', 'coverage: spec fields'],
      requirements: ['Preview boundary is clear', 'Coverage gaps remain visible'],
      evidence: ['Preview frame'],
      review: ['Preview requires completed acceptance criteria'],
      handoff: ['Preview evidence is included as a local snapshot reference only'],
    },
    {
      id: 'node-6',
      parentId: 'phase-3',
      level: 'task',
      index: '06',
      label: 'Decision',
      type: 'decision',
      typeLabel: 'Gate',
      x: 20,
      y: 80,
      status: 'needs-lock',
      family: 'decision',
      familyLabel: 'Decision',
      title: 'Point Decision',
      subtitle: 'Keeps unresolved approvals visible before handoff.',
      readiness: 'needs-decision',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Surfaces unresolved approval points that must be locked before a handoff is available.',
      config: 'Point lock board',
      model: 'Human decision',
      inputs: ['Draft build spec', 'Advisory findings'],
      outputs: ['Locked decisions'],
      guardrails: ['Point lock required', 'Defer remains available'],
      trace: ['page: Decisions', 'decision: D-005'],
      requirements: ['Point choice recorded', 'Deferred choices continue to block handoff'],
      evidence: ['Decision D-005 status'],
      review: ['Codex handoff gating remains unresolved'],
      handoff: ['All blocking Decisions must be locked or deferred before handoff can be prepared'],
    },
    {
      id: 'node-7',
      parentId: 'phase-3',
      level: 'task',
      index: '07',
      label: 'Trace Evidence',
      type: 'trace',
      typeLabel: 'Evidence',
      x: 50,
      y: 82,
      status: 'draft',
      family: 'evidence',
      familyLabel: 'Evidence',
      title: 'Trace Evidence Map',
      subtitle: 'Links sources, spec fields, decisions, and artifact readiness.',
      readiness: 'needs-evidence',
      blockerCount: 2,
      evidenceCount: 4,
      description: 'Links sources, fields, decisions and artifact readiness so handoff packets remain auditable.',
      config: 'Source-target links',
      model: 'Trace table',
      inputs: ['Included context set', 'Locked decisions'],
      outputs: ['Evidence map'],
      guardrails: ['Missing links warned', 'No export while incomplete'],
      trace: ['page: Trace & Evidence', 'table: trace links'],
      requirements: ['Each required spec field has evidence', 'Missing links stay visible'],
      evidence: ['Trace table rows', 'Missing evidence warning', 'Source-target map', 'Decision link'],
      review: ['Trace Review: missing evidence links'],
      handoff: ['Evidence map must be reviewed locally before handoff unlocks'],
    },
    // Under phase-4 (Handoff Phase)
    {
      id: 'node-8',
      parentId: 'phase-4',
      level: 'task',
      index: '08',
      label: 'Handoff Packet',
      type: 'handoff',
      typeLabel: 'Handoff',
      x: 80,
      y: 82,
      status: 'blocked',
      family: 'handoff',
      familyLabel: 'Handoff Packet',
      title: 'Handoff Packet',
      subtitle: 'Collects ready artifacts without writing to a repo.',
      readiness: 'blocked',
      blockerCount: 5,
      evidenceCount: 1,
      description: 'Prepares a handoff preview only after specs, decisions and evidence are ready.',
      config: 'Packet preview',
      model: 'No AI execution',
      inputs: ['Evidence map', 'Locked decisions'],
      outputs: ['Handoff preview'],
      guardrails: ['Repo writes handoff only', 'Button gated until ready'],
      trace: ['page: handoff manifest', 'gate: appState.handoffReady'],
      requirements: ['Spec validated', 'Decisions locked', 'Evidence reviewed', 'Review items acknowledged'],
      evidence: ['Handoff manifest preview'],
      review: ['Codex Handoff Review: not ready'],
      handoff: ['Prepare handoff remains disabled until all local readiness checks pass'],
    },
  ],

  nodePalette: [
    { type: 'intake', label: 'Context Node', description: 'Human goal and constraint capture', icon: 'spark' },
    { type: 'context', label: 'Context Node', description: 'Safe source selection', icon: 'branch' },
    { type: 'spec', label: 'Work Packet', description: 'Controlled spec fields', icon: 'document' },
    { type: 'review', label: 'Review Gate', description: 'Inspect-only review cards', icon: 'review' },
    { type: 'preview', label: 'Evidence', description: 'Local evidence snapshot', icon: 'eye' },
    { type: 'decision', label: 'Decision', description: 'Point lock decisions', icon: 'lock' },
    { type: 'trace', label: 'Evidence', description: 'Source-to-target links', icon: 'trace' },
    { type: 'handoff', label: 'Handoff Packet', description: 'Gated packet preview', icon: 'archive' },
  ],

  // Visual-only links drawn on the Workbench canvas.
  workflowEdges: [
    { source: 'node-1', target: 'node-2', tone: 'validated' },
    { source: 'node-2', target: 'node-3', tone: 'validated' },
    { source: 'node-3', target: 'node-4', tone: 'pending' },
    { source: 'node-4', target: 'node-5', tone: 'pending' },
    { source: 'node-5', target: 'node-6', tone: 'pending' },
    { source: 'node-6', target: 'node-7', tone: 'risk' },
    { source: 'node-7', target: 'node-8', tone: 'neutral' },
    { source: 'node-3', target: 'node-5', tone: 'neutral' },
  ],

  // Visual-only hierarchical links connecting nodes at identical levels inside matching folders
  hierarchicalEdges: [
    // L1: Requirements
    { source: 'req-1', target: 'req-2', tone: 'pending' },

    // L2: Architecture modules under req-1
    { source: 'arch-1', target: 'arch-2', tone: 'pending' },

    // L3: Components under their respective parents
    { source: 'comp-1', target: 'comp-2', tone: 'validated' },
    { source: 'comp-3', target: 'comp-4', tone: 'pending' },
    { source: 'comp-5', target: 'comp-6', tone: 'neutral' },

    // L4: Phases under their respective parents
    { source: 'phase-2', target: 'phase-3', tone: 'pending' },

    // L5: Tasks under their respective parents
    { source: 'node-1', target: 'node-2', tone: 'validated' },
    { source: 'node-4', target: 'node-5', tone: 'pending' },
    { source: 'node-5', target: 'node-6', tone: 'pending' },
    { source: 'node-6', target: 'node-7', tone: 'risk' },
  ],

  workbenchBoard: {
    width: 3200,
    height: 1780,
    zones: [
      { id: 'zone-requirements', label: 'Product requirements', x: 120, y: 120, width: 1020, height: 330 },
      { id: 'zone-architecture', label: 'Architecture modules', x: 120, y: 540, width: 1280, height: 430 },
      { id: 'zone-components', label: 'Software components', x: 1500, y: 120, width: 1040, height: 700 },
      { id: 'zone-phases', label: 'Delivery phases', x: 1500, y: 900, width: 1260, height: 360 },
      { id: 'zone-tasks', label: 'Task flow and handoff path', x: 320, y: 1340, width: 2320, height: 280 },
    ],
    nodePositions: {
      'req-1': { x: 410, y: 286 },
      'req-2': { x: 840, y: 286 },
      'arch-1': { x: 400, y: 705 },
      'arch-2': { x: 790, y: 705 },
      'arch-3': { x: 1180, y: 705 },
      'comp-1': { x: 1690, y: 310 },
      'comp-2': { x: 2020, y: 310 },
      'comp-3': { x: 2350, y: 310 },
      'comp-4': { x: 1690, y: 610 },
      'comp-5': { x: 2020, y: 610 },
      'comp-6': { x: 2350, y: 610 },
      'phase-1': { x: 1690, y: 1065 },
      'phase-2': { x: 2020, y: 1065 },
      'phase-3': { x: 2350, y: 1065 },
      'phase-4': { x: 2680, y: 1065 },
      'node-1': { x: 490, y: 1480 },
      'node-2': { x: 770, y: 1480 },
      'node-3': { x: 1050, y: 1480 },
      'node-4': { x: 1330, y: 1480 },
      'node-5': { x: 1610, y: 1480 },
      'node-6': { x: 1890, y: 1480 },
      'node-7': { x: 2170, y: 1480 },
      'node-8': { x: 2450, y: 1480 },
    },
  },

  // Architecture graph used by the workflow explainer. These nodes mirror the
  // Workbench canvas and describe local artifact flow.
  architectureGraphNodes: [
    {
      id: 'arch-node-selected',
      label: 'Source context',
      linkedNodeId: 'node-1',
      role: 'Point-provided context is captured as local, inspect-only source material.',
      output: 'Selected source context',
    },
    {
      id: 'arch-context-basket',
      label: 'Governed spec',
      linkedNodeId: 'node-3',
      role: 'The selected context is shaped into controlled spec fields and acceptance criteria.',
      output: 'Governed spec draft',
    },
    {
      id: 'arch-assistant-chat',
      label: 'Decision/evidence gate',
      linkedNodeId: 'node-6',
      role: 'D-005 keeps the handoff preview unavailable until evidence, criteria, and Point lock are clear.',
      output: 'Governance checkpoint',
    },
    {
      id: 'arch-handoff-preview',
      label: 'Handoff preview',
      linkedNodeId: 'node-8',
      role: 'A packet preview shows what would be handed off after the local gates clear.',
      output: 'Handoff preview',
    },
  ],

  architectureGraphEdges: [
    { source: 'arch-node-selected', target: 'arch-context-basket', label: 'Select safe context' },
    { source: 'arch-context-basket', target: 'arch-assistant-chat', label: 'Check D-005 gate' },
    { source: 'arch-assistant-chat', target: 'arch-handoff-preview', label: 'Show preview only' },
  ],

  primaryDemoPath: {
    id: 'primary-workflow',
    name: 'context -> governed spec -> decision/evidence gate -> handoff preview',
    status: 'blocked',
    summary: 'Primary workflow for turning selected context into a governed spec and a gated handoff preview.',
    currentCheckpoint: 'D-005 Codex handoff gating',
    stages: [
      {
        id: 'source-context-stage',
        label: 'Source context',
        page: 'Workbench',
        linkedNodeId: 'node-2',
        status: 'selected',
        evidenceIds: ['source-context'],
        summary: 'Selected context includes the goal brief, Context Selector, Spec Builder, and Handoff Packet nodes while protected exclusions stay sealed.',
      },
      {
        id: 'governed-spec',
        label: 'Governed spec',
        page: 'Spec Builder',
        linkedNodeId: 'node-3',
        status: 'needs-criteria',
        evidenceIds: ['source-context'],
        summary: 'Spec draft fields are visible, but acceptance criteria must be locked before readiness clears.',
      },
      {
        id: 'decision-evidence-gate',
        label: 'Decision/evidence gate',
        page: 'Decisions + Trace & Evidence',
        linkedNodeId: 'node-6',
        status: 'waiting',
        evidenceIds: ['locked-decision', 'validation-readiness'],
        summary: 'D-005 is the governance checkpoint for Codex handoff readiness.',
      },
      {
        id: 'handoff-preview',
        label: 'Handoff preview',
        page: 'Preview',
        linkedNodeId: 'node-8',
        status: 'mock-preview',
        evidenceIds: ['handoff-preview-evidence'],
        summary: 'The handoff packet preview never writes files or calls services.',
      },
    ],
    blockers: [
      {
        id: 'missing-acceptance-criteria',
        label: 'Acceptance criteria missing',
        status: 'open',
        blocks: 'Handoff readiness',
      },
      {
        id: 'missing-evidence',
        label: 'Required evidence missing or unreviewed',
        status: 'open',
        blocks: 'Handoff readiness',
      },
      {
        id: 'decision-lock-open',
        label: 'D-005 Decision open',
        status: 'open',
        blocks: 'Handoff readiness',
      },
    ],
    evidenceItems: [
      {
        id: 'source-context',
        type: 'source_context',
        label: 'Source context evidence',
        sourceObjectId: 'node-2',
        targetObjectId: 'spec-draft-primary',
        status: 'attached',
        requiredForHandoff: true,
        summary: 'Selected Context is visible on Workbench and excludes runtime state, secrets, and repo write authority.',
      },
      {
        id: 'locked-decision',
        type: 'decision',
        label: 'D-005 Decision evidence',
        sourceObjectId: 'D-005',
        targetObjectId: 'handoff-preview',
        status: 'missing',
        requiredForHandoff: true,
        summary: 'Missing until Point locks D-005 for the handoff preview.',
      },
      {
        id: 'validation-readiness',
        type: 'validation_result',
        label: 'Validation readiness evidence',
        sourceObjectId: 'validation-local-readiness',
        targetObjectId: 'handoff-preview',
        status: 'warning',
        requiredForHandoff: true,
        summary: 'Readiness is waiting while spec fields, evidence review, or D-005 are unresolved.',
      },
      {
        id: 'handoff-preview-evidence',
        type: 'artifact_reference',
        label: 'Handoff preview evidence',
        sourceObjectId: 'handoff-preview',
        targetObjectId: 'handoff-preview',
        status: 'attached',
        requiredForHandoff: true,
        summary: 'The preview exists as local browser data only and is not a produced handoff artifact.',
      },
    ],
  },

  // Initial context items included in the basket.
  contextItems: [
    {
      id: 'node-1',
      label: 'Selected context: Goal Intake',
    },
    {
      id: 'node-2',
      label: 'Selected context: Context Selector',
    },
  ],

  // Protected exclusions that cannot be added to AI context.
  protectedItems: [
    { id: 'runtime-state', label: 'Runtime state', status: 'excluded' },
    { id: 'secrets', label: 'Secrets', status: 'excluded' },
    { id: 'repo-write', label: 'Repo write authority', status: 'excluded' },
  ],

  assistantTranscript: [
    {
      speaker: 'user',
      text: 'Use the selected context to prepare a governed spec and a gated Codex handoff preview.',
    },
    {
      speaker: 'assistant',
      text: 'I can show a packet preview from safe context only. Runtime state, secrets, repo write authority, APIs, and external connectors remain excluded.',
    },
    {
      speaker: 'assistant',
      text: 'D-005 keeps the preview unavailable until acceptance criteria, evidence review, and the Point lock are clear locally.',
    },
  ],

  handoffPacketPreview: {
    packet_id: 'OPENCLAW-HANDOFF-PREVIEW-001',
    title: 'Primary Workflow Handoff Preview',
    status: 'mock-preview',
    primary_demo_path: 'context -> governed spec -> decision/evidence gate -> handoff preview',
    objective: 'Align selected context into a governed spec and a D-005-gated handoff preview.',
    gate: {
      decision_id: 'D-005',
      name: 'Codex handoff gating',
      checkpoint: 'Governance checkpoint before the handoff preview can be marked ready.',
      status: 'needs-lock',
    },
    allowed_paths: [
      'Local app screens and interaction state',
      'Schema and QA references',
      'Evidence notes',
      'Operational status note',
    ],
    forbidden_actions: [
      'No new platform services',
      'No backend, API, auth, database, storage, or deployment',
      'No runtime state mutation',
      'No live repository scanning or external connectors',
      'Secrets remain excluded',
      'Changes stay inside the approved workspace scope',
    ],
    required_work: [
      'Show selected context and protected exclusions on Workbench',
      'Show governed spec fields and acceptance-criteria readiness on Spec Builder',
      'Show D-005 as the Codex handoff governance checkpoint',
      'Show context, spec, decision, validation, and preview evidence links',
      'Keep the handoff preview local-only',
    ],
    acceptance_criteria: [
      'The user can visually follow context -> governed spec -> decision/evidence gate -> handoff preview',
      'D-005 is visible as the handoff gating decision',
      'Missing acceptance criteria, evidence, or open Decision state keeps readiness unavailable',
      'The preview remains local-only',
      'Readiness checks pass',
    ],
    validation_commands: ['Local validation suite', 'Diff cleanliness check'],
    stop_conditions: [
      'Stop if a dependency is required',
      'Stop if backend/API/auth/database/deployment is needed',
      'Stop if real repo or external connector access is needed',
      'Stop if changes would move outside the approved workspace scope',
      'Stop if validation fails and cannot be fixed within scope',
      'Stop if a product or architecture decision is required',
    ],
    final_response_format: [
      'Verdict:',
      'Changed files:',
      'Validation output:',
      'Evidence recorded:',
      'Risks:',
      'Next recommended action:',
    ],
    selected_context: ['Selected context: Context Selector', 'Governed spec: Spec Builder', 'Handoff preview: Handoff Packet', 'Source context: primary workflow brief'],
    protected_exclusions: ['Runtime state', 'Secrets', 'Repo write authority'],
    included_evidence_ids: ['source-context', 'locked-decision', 'validation-readiness', 'handoff-preview-evidence'],
    included_decision_ids: ['D-005'],
    readiness: 'blocked',
    blocked_by: ['Acceptance criteria missing', 'D-005 needs Point lock', 'Required evidence is missing or unreviewed'],
  },

  evidenceItems: [
    {
      id: 'source-context',
      type: 'source_context',
      label: 'Source context evidence',
      sourceObjectId: 'node-2',
      targetObjectId: 'spec-draft-primary',
      status: 'attached',
      requiredForHandoff: true,
      summary: 'Selected Context is visible on Workbench and excludes runtime state, secrets, and repo write authority.',
    },
    {
      id: 'locked-decision',
      type: 'decision',
      label: 'D-005 Decision evidence',
      sourceObjectId: 'D-005',
      targetObjectId: 'handoff-preview',
      status: 'missing',
      requiredForHandoff: true,
      summary: 'Missing until Point locks D-005 for the handoff preview.',
    },
    {
      id: 'validation-readiness',
      type: 'validation_result',
      label: 'Validation readiness evidence',
        sourceObjectId: 'validation-local-readiness',
      targetObjectId: 'handoff-preview',
      status: 'warning',
      requiredForHandoff: true,
      summary: 'Readiness is waiting while spec fields, evidence review, or D-005 are unresolved.',
    },
    {
      id: 'handoff-preview-evidence',
      type: 'artifact_reference',
      label: 'Handoff preview evidence',
      sourceObjectId: 'handoff-preview',
      targetObjectId: 'handoff-preview',
      status: 'attached',
      requiredForHandoff: true,
      summary: 'The preview exists as local data only and is not a produced handoff artifact.',
    },
  ],

  artifactRefs: [
    {
      id: 'artifact-static-mvp',
      type: 'static_html_app',
      status: 'needs_sync',
      label: 'COCKPIT-MVP-014 local preview',
      linkedObjectIds: ['project-cooperative-cockpit-static-mvp', 'spec-draft-primary'],
    },
    {
      id: 'artifact-handoff-preview',
      type: 'handoff_placeholder',
      status: 'handoff_only',
      label: 'Handoff preview',
      linkedObjectIds: ['work-packet-primary-workflow', 'handoff-packet-primary-workflow'],
    },
  ],

  workPacket: {
    id: 'work-packet-primary-workflow',
    title: 'GOAL-007 Cockpit Work Packet',
    objective: 'Surface Work Packet and derived Handoff Packet readiness in existing pages and panels using local data only.',
    allowedPaths: [
      'Local app screens and interaction state',
      'Local data model',
      'Visual styles',
      'QA checklist',
      'Evidence notes',
    ],
    forbiddenActions: [
      'No new dependencies',
      'No backend, API, auth, database, or deployment',
      'No live workflow execution',
      'No live agent orchestration',
      'No external connectors',
      'No secrets or credentials',
      'No file exports',
      'No repository writes from the app',
      'No filesystem access',
      'No new pages',
    ],
    acceptanceCriteria: [
      'Work Packet is visible',
      'Handoff Packet is clearly derived',
      'Handoff does not perform real export or repo write',
      'Readiness reflects local state',
      'All eight pages remain',
      'Readiness checks pass',
    ],
    validationCommands: ['Local validation suite'],
    status: 'draft',
  },

  handoffPacket: {
    id: 'handoff-packet-primary-workflow',
    workPacketId: 'work-packet-primary-workflow',
    readiness: 'handoff_blocked',
    derivedFrom: ['work-packet-primary-workflow', 'D-005', 'source-context', 'locked-decision', 'validation-readiness'],
    blockedBy: [
      'Acceptance criteria remains incomplete',
      'D-005 needs Point lock locally',
      'Required evidence is missing or unreviewed',
      'Validation result remains warning or waiting',
    ],
    includedEvidenceIds: ['source-context', 'locked-decision', 'validation-readiness', 'handoff-preview-evidence'],
    includedDecisionIds: ['D-005'],
  },

  agentRoles: [
    {
      id: 'role-planner',
      name: 'Planner',
      purpose: 'Break bounded cockpit work into scoped tasks and acceptance checks.',
      mustNotDo: ['Add runtime orchestration', 'Expand product scope without Point lock'],
    },
    {
      id: 'role-reviewer',
      name: 'Reviewer',
      purpose: 'Inspect workspace artifacts, findings, decisions, and evidence without modifying runtime state.',
      mustNotDo: ['Auto-fix source files from the UI', 'Call external services'],
    },
    {
      id: 'role-qa',
      name: 'QA',
      purpose: 'Run local validation and smoke checks against the workspace boundary.',
      mustNotDo: ['Claim tests passed without running them', 'Treat local validation as live execution'],
    },
  ],

  // Specification fields and their statuses.
  specFields: [
    {
      id: 'objective',
      name: 'Objective',
      value: 'Align context to a governed spec and gated handoff preview.',
      status: 'draft',
      suggestion: 'Keep the path local: context -> governed spec -> decision/evidence gate -> handoff preview.',
      evidenceIds: ['source-context'],
    },
    {
      id: 'layout-regions',
      name: 'Layout regions',
      value: 'Home summary, Workbench selected context, Spec Builder fields, Decisions gate, Trace evidence, Preview handoff evidence',
      status: 'draft',
      suggestion: 'List the primary UI regions (header, sidebar, canvas, inspector, footer).',
      evidenceIds: ['source-context', 'handoff-preview-evidence'],
    },
    {
      id: 'interaction-states',
      name: 'Interaction states',
      value: 'Waiting on missing acceptance criteria, missing evidence, or open D-005 lock; ready remains local-only.',
      status: 'draft',
      suggestion: 'Describe waiting and ready handoff readiness states.',
      evidenceIds: ['validation-readiness', 'locked-decision'],
    },
    {
      id: 'protected-surfaces',
      name: 'Protected surfaces',
      value: 'Runtime state, Secrets, Repo write authority',
      status: 'locked',
      suggestion: '',
      evidenceIds: ['source-context'],
    },
    {
      id: 'acceptance-criteria',
      name: 'Acceptance criteria',
      value: '',
      status: 'missing',
      suggestion: 'Confirm the primary path, D-005 gate, evidence links, waiting state, and local-only preview.',
      evidenceIds: [],
    },
    {
      id: 'validation-method',
      name: 'Validation method',
      value: '',
      status: 'needs-lock',
      suggestion: 'Use npm run validate plus manual workspace navigation and no-network checks.',
      evidenceIds: ['validation-readiness'],
    },
  ],

  // Review results definitions.
  reviewResults: [
    {
      id: 'review-architecture',
      name: 'Architecture Review',
      verdict: 'Revise',
      severity: 'high',
      findings: 8,
      details: [
        'Clarify separation of concerns',
        'Define layers for context, spec, review and handoff',
        'Ensure traceability across nodes',
      ],
    },
    {
      id: 'review-security',
      name: 'Security Review',
      verdict: 'Pass with notes',
      severity: 'medium',
      findings: 3,
      details: ['No secrets in context', 'Ensure governance strip visible', 'Review agent scopes'],
    },
    {
      id: 'review-redteam',
      name: 'Red Team Review',
      verdict: '2 high‑risk ambiguities',
      severity: 'high',
      findings: 2,
      details: ['Ambiguous spec field definitions', 'Potential misuse of review actions'],
    },
    {
      id: 'review-ux',
      name: 'UX Review',
      verdict: 'Preview required',
      severity: 'low',
      findings: 1,
      details: ['UX notes missing acceptance criteria'],
    },
    {
      id: 'review-trace',
      name: 'Trace Review',
      verdict: 'Missing evidence links',
      severity: 'medium',
      findings: 2,
      details: ['Some spec fields lack traceability to source context', 'Missing link between node and preview'],
    },
    {
      id: 'review-codex',
      name: 'Codex Handoff Review',
      verdict: 'Not ready',
      severity: 'high',
      findings: 3,
      details: ['Spec incomplete', 'Decisions unresolved', 'Preview out of sync'],
    },
  ],

  reviewRun: {
    id: 'review-run-primary-workflow',
    name: 'Primary workflow review',
    status: 'review_complete',
    scopeContextIds: ['node-2', 'node-3', 'node-6', 'node-8'],
    findingIds: ['finding-spec-fields-open', 'finding-d005-open', 'finding-evidence-warning'],
    verdict: 'Not ready for handoff until readiness checks clear',
  },

  findings: [
    {
      id: 'finding-spec-fields-open',
      reviewRunId: 'review-run-primary-workflow',
      severity: 'high',
      status: 'finding_open',
      summary: 'Spec draft is waiting on acceptance criteria and validation method fields.',
      recommendation: 'Keep handoff readiness unavailable until required spec fields are locked locally.',
      evidenceIds: ['validation-readiness'],
    },
    {
      id: 'finding-d005-open',
      reviewRunId: 'review-run-primary-workflow',
      severity: 'high',
      status: 'finding_open',
      summary: 'D-005 remains the visible Point-lock gate for handoff readiness.',
      recommendation: 'Keep D-005 in the Needs Point lock lane until the local decision is locked.',
      evidenceIds: ['locked-decision'],
    },
    {
      id: 'finding-evidence-warning',
      reviewRunId: 'review-run-primary-workflow',
      severity: 'medium',
      status: 'finding_open',
      summary: 'Evidence review is incomplete for the handoff preview.',
      recommendation: 'Require local evidence review before enabling handoff readiness.',
      evidenceIds: ['source-context', 'handoff-preview-evidence'],
    },
  ],

  // Decision definitions.
  decisions: [
    {
      id: 'D-001',
      title: 'Selected Context placement',
      description: 'Should the Selected Context panel be docked or floating?',
      status: 'locked',
      options: ['Floating', 'Docked', 'Collapsible'],
      selectedOption: 'Docked',
      chosenOption: 'Docked',
      requiresPointLock: false,
    },
    {
      id: 'D-002',
      title: 'Spec Builder access',
      description: 'Tab only or dedicated page?',
      status: 'locked',
      options: ['Tab', 'Page', 'Both'],
      selectedOption: 'Both',
      chosenOption: 'Both',
      requiresPointLock: false,
    },
    {
      id: 'D-003',
      title: 'Review action language',
      description: 'What wording should be used for review actions?',
      status: 'locked',
      // Avoid unsafe execution-style wording on action labels. Offer only compliant options.
      options: ['Validate', 'Start review checks'],
      selectedOption: 'Validate',
      chosenOption: 'Validate',
      requiresPointLock: false,
    },
    {
      id: 'D-004',
      title: 'Preview naming',
      description: 'Name of the preview tab/page',
      status: 'locked',
      options: ['Preview', 'UI / HTML Viewer'],
      selectedOption: 'Preview',
      chosenOption: 'Preview',
      requiresPointLock: false,
    },
    {
      id: 'D-005',
      title: 'Codex handoff gating',
      description: 'Governance checkpoint for when the Codex handoff preview can be marked ready.',
      status: 'needs-lock',
      options: ['Gated until ready', 'Hold unavailable'],
      selectedOption: null,
      chosenOption: null,
      requiresPointLock: true,
      gates: ['handoff-preview'],
      evidenceIds: ['locked-decision', 'validation-readiness'],
    },
  ],

  // Simple trace links. Each link points from a source to a target by id.
  traceLinks: [
    { source: 'node-1', target: 'objective' },
    { source: 'node-2', target: 'layout-regions' },
    { source: 'node-2', target: 'interaction-states' },
    { source: 'source-context', target: 'objective' },
    { source: 'locked-decision', target: 'D-005' },
    { source: 'validation-readiness', target: 'validation-method' },
    { source: 'handoff-preview-evidence', target: 'handoff-preview' },
    { source: 'spec-field', target: 'D-005' },
  ],

  validationResults: [
    {
      id: 'validation-local-readiness',
      scope: 'Primary workflow',
      status: 'validation_blocked',
      command: 'npm run validate',
      summary: 'Repo validation may pass while handoff readiness remains waiting on local criteria.',
      evidenceRef: 'validation-readiness',
    },
    {
      id: 'validation-manual-local-preview',
      scope: 'Manual eight-page workspace smoke check',
      status: 'validation_warning',
      command: 'Manual browser check',
      summary: 'All eight pages must remain reachable without network/API calls before review use.',
      evidenceRef: 'handoff-preview-evidence',
    },
  ],

  // Safety rules definitions for Rules & Scope page.
  rules: [
    {
      name: 'Runtime mutation',
      allowed: false,
      reviewGate: 'Unavailable by default',
      notes: '',
    },
    {
      name: 'Repo writes',
      allowed: false,
      reviewGate: 'Handoff only',
      notes: '',
    },
    {
      name: 'Artifact drafting',
      allowed: true,
      reviewGate: 'Spec builder allowed',
      notes: '',
    },
    {
      name: 'Dynamic UI',
      allowed: true,
      reviewGate: 'Spec first',
      notes: '',
    },
    {
      name: 'Secrets',
      allowed: false,
      reviewGate: 'Excluded',
      notes: '',
    },
    {
      name: 'External actions',
      allowed: false,
      reviewGate: 'Unavailable',
      notes: '',
    },
    {
      name: 'Review agents',
      allowed: true,
      reviewGate: 'Inspect only',
      notes: '',
    },
    {
      name: 'Codex handoff',
      allowed: true,
      reviewGate: 'Gated until ready',
      notes: '',
    },
  ],
};
