// Static mock data for the OpenClaw Cooperative Cockpit MVP.

/*
  This file defines the data used by the front‑end prototype. All values
  are fixed and do not come from any external service. You can adjust
  coordinates or labels here to reposition nodes on the Workbench.
*/

window.mockData = {
  workspace: {
    id: 'workspace-static-mvp',
    name: 'OpenClaw Static MVP Workspace',
    mode: 'static_local_only',
    constraints: [
      'No backend, API, auth, database, deployment, or external connectors',
      'No runtime workflow execution or real agent orchestration',
      'No repo writes from the static prototype',
    ],
  },

  project: {
    id: 'project-cooperative-cockpit-static-mvp',
    name: 'OpenClaw Cooperative Cockpit Static MVP',
    artifactId: 'COCKPIT-MVP-014',
    summary: 'Static local prototype for governed context, spec, review, evidence, decision, and handoff readiness flows.',
    currentStage: 'GOAL-005 mock data normalization',
    status: 'draft',
  },

  contextNodes: [
    {
      id: 'node-1',
      label: 'User Input / Concept Intake',
      type: 'intake',
      status: 'validated',
      description: 'Captures the human-provided goal, constraints and stop conditions before any drafting begins.',
      x: 20,
      y: 24,
      links: ['node-2', 'objective'],
    },
    {
      id: 'node-2',
      label: 'Context Selector',
      type: 'context',
      status: 'validated',
      description: 'Chooses safe source material for the spec while keeping protected surfaces excluded.',
      x: 50,
      y: 20,
      links: ['node-3', 'source-context'],
    },
    {
      id: 'node-3',
      label: 'Spec Builder',
      type: 'spec',
      status: 'draft',
      description: 'Turns the selected context into controlled fields, acceptance criteria and handoff gates.',
      x: 80,
      y: 32,
      links: ['node-4', 'spec-draft-primary'],
    },
    {
      id: 'node-6',
      label: 'Decision Lock',
      type: 'decision',
      status: 'needs-lock',
      description: 'Surfaces unresolved approval points that must be locked before a handoff is available.',
      x: 20,
      y: 80,
      links: ['D-005', 'handoff-preview'],
    },
    {
      id: 'node-8',
      label: 'Handoff Packet',
      type: 'handoff',
      status: 'blocked',
      description: 'Prepares a static placeholder bundle only after specs, decisions and evidence are ready.',
      x: 80,
      y: 82,
      links: ['work-packet-primary-demo', 'handoff-packet-primary-demo'],
    },
  ],

  selectedContext: {
    includedIds: ['node-2', 'node-3', 'node-8', 'golden-path-brief'],
    protectedExclusions: [
      { id: 'runtime-state', label: 'Runtime state', status: 'excluded' },
      { id: 'secrets', label: 'Secrets', status: 'excluded' },
      { id: 'repo-write', label: 'Repo write authority', status: 'excluded' },
    ],
  },

  specTemplates: [
    {
      id: 'template-product-spec',
      name: 'Product Spec',
      description: 'Structures objective, protected surfaces, acceptance criteria, and validation method.',
      fieldIds: ['objective', 'layout-regions', 'interaction-states', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    },
    {
      id: 'template-review-brief',
      name: 'Review Brief',
      description: 'Frames inspect-only review context and finding evidence expectations.',
      fieldIds: ['objective', 'interaction-states', 'protected-surfaces', 'validation-method'],
    },
    {
      id: 'template-codex-handoff',
      name: 'Codex Handoff',
      description: 'Collects bounded implementation scope, forbidden actions, acceptance criteria, and validation commands.',
      fieldIds: ['objective', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    },
  ],

  specDraft: {
    id: 'spec-draft-primary',
    templateId: 'template-product-spec',
    status: 'draft',
    fieldIds: ['objective', 'layout-regions', 'interaction-states', 'protected-surfaces', 'acceptance-criteria', 'validation-method'],
    readiness: 'blocked',
  },

  // Nodes displayed on the Workbench canvas. Coordinates are percentages
  // relative to the canvas container for quick placement. These are static
  // workflow operators; they do not call models, services or runtime tools.
  nodes: [
    {
      id: 'node-1',
      index: '01',
      label: 'User Input / Concept Intake',
      type: 'intake',
      typeLabel: 'Input',
      x: 20,
      y: 24,
      status: 'validated',
      family: 'context',
      familyLabel: 'Context Node',
      title: 'Goal Intake',
      subtitle: 'Frames the Work Packet before drafting.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 2,
      description: 'Captures the human-provided goal, constraints and stop conditions before any drafting begins.',
      config: 'Goal brief + allowed paths',
      model: 'Human-authored',
      inputs: ['Point brief', 'Goal template'],
      outputs: ['Scoped concept packet'],
      guardrails: ['No runtime mutation', 'No hidden external calls'],
      trace: ['source: goal brief', 'decision: static prototype only'],
      requirements: ['Goal and stop conditions captured', 'Allowed paths and static constraint stated'],
      evidence: ['Goal template linked', 'Static prototype constraint recorded'],
      review: ['No execution verbs required', 'Human-authored context remains inspect-only'],
      handoff: ['Feeds the scoped concept packet into the Work Packet'],
    },
    {
      id: 'node-2',
      index: '02',
      label: 'Context Selector',
      type: 'context',
      typeLabel: 'Context',
      x: 50,
      y: 20,
      status: 'validated',
      family: 'context',
      familyLabel: 'Context Node',
      title: 'Safe Context Basket',
      subtitle: 'Separates usable context from protected exclusions.',
      readiness: 'ready',
      blockerCount: 0,
      evidenceCount: 3,
      description: 'Chooses safe source material for the spec while keeping protected surfaces excluded.',
      config: 'Context basket policy',
      model: 'Static selector',
      inputs: ['Scoped concept packet', 'Protected exclusions'],
      outputs: ['Included context set'],
      guardrails: ['Secrets excluded', 'Repo write authority excluded'],
      trace: ['source: context basket', 'evidence: exclusions list'],
      requirements: ['Protected exclusions remain sealed', 'Included context stays local to the browser'],
      evidence: ['Context Basket item list', 'Protected Exclusions list', 'Local mock state only'],
      review: ['Secrets and repo write authority remain excluded'],
      handoff: ['Included context becomes Handoff Packet source material only after gates pass'],
    },
    {
      id: 'node-3',
      index: '03',
      label: 'Spec Builder',
      type: 'spec',
      typeLabel: 'Draft',
      x: 80,
      y: 32,
      status: 'draft',
      family: 'spec',
      familyLabel: 'Work Packet',
      title: 'Spec Assembly',
      subtitle: 'Turns context into controlled artifact requirements.',
      readiness: 'draft',
      blockerCount: 3,
      evidenceCount: 2,
      description: 'Turns the selected context into controlled fields, acceptance criteria and handoff gates.',
      config: 'UI / UX Spec template',
      model: 'Stub suggestions',
      inputs: ['Included context set'],
      outputs: ['Draft build spec'],
      guardrails: ['Human locks required', 'Unsafe action labels blocked'],
      trace: ['target: spec fields', 'decision: template set'],
      requirements: ['Required fields resolved', 'Human locks applied before handoff'],
      evidence: ['Spec fields table', 'Template decision record'],
      review: ['Missing fields block readiness', 'Static suggestions do not call AI services'],
      handoff: ['Locked Work Packet is required before preparing a Handoff Packet'],
    },
    {
      id: 'node-4',
      index: '04',
      label: 'Review Agent',
      type: 'review',
      typeLabel: 'Review',
      x: 34,
      y: 56,
      status: 'needs-lock',
      family: 'review',
      familyLabel: 'Review Gate',
      title: 'Advisory Review',
      subtitle: 'Collects inspect-only review findings and blockers.',
      readiness: 'review-blocked',
      blockerCount: 2,
      evidenceCount: 2,
      description: 'Provides inspect-only review findings and advisory notes without changing runtime or repository state.',
      config: 'Inspect-only checks',
      model: 'Mock review set',
      inputs: ['Draft build spec', 'Included context set'],
      outputs: ['Advisory findings'],
      guardrails: ['No auto-fix', 'No repository writes'],
      trace: ['page: Review Runs', 'evidence: finding cards'],
      requirements: ['Findings are advisory only', 'High-risk ambiguities are visible before handoff'],
      evidence: ['Review Runs page', 'Finding cards'],
      review: ['Architecture Review: revise', 'Red Team Review: high-risk ambiguities'],
      handoff: ['Review blockers must be acknowledged locally before a mock handoff can unlock'],
    },
    {
      id: 'node-5',
      index: '05',
      label: 'Preview Renderer',
      type: 'preview',
      typeLabel: 'Preview',
      x: 65,
      y: 58,
      status: 'needs-sync',
      family: 'evidence',
      familyLabel: 'Evidence',
      title: 'Static Preview Evidence',
      subtitle: 'Shows local artifact coverage without rendering real output.',
      readiness: 'needs-evidence',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Shows a static artifact preview and coverage state without generating or executing code.',
      config: 'Static HTML viewer',
      model: 'Placeholder renderer',
      inputs: ['Draft build spec', 'Advisory findings'],
      outputs: ['Static preview state'],
      guardrails: ['No real generation', 'No external assets'],
      trace: ['page: UI / HTML Viewer', 'coverage: spec fields'],
      requirements: ['Preview is clearly static', 'Coverage gaps remain visible'],
      evidence: ['Static preview frame'],
      review: ['Preview requires completed acceptance criteria'],
      handoff: ['Preview evidence is included as a local snapshot reference only'],
    },
    {
      id: 'node-6',
      index: '06',
      label: 'Decision Lock',
      type: 'decision',
      typeLabel: 'Gate',
      x: 20,
      y: 80,
      status: 'needs-lock',
      family: 'decision',
      familyLabel: 'Decision Lock',
      title: 'Point Decision Lock',
      subtitle: 'Keeps unresolved approvals visible before handoff.',
      readiness: 'needs-decision',
      blockerCount: 1,
      evidenceCount: 1,
      description: 'Surfaces unresolved approval points that must be locked before a handoff is available.',
      config: 'Point lock board',
      model: 'Human decision',
      inputs: ['Draft build spec', 'Advisory findings'],
      outputs: ['Locked decisions'],
      guardrails: ['Point lock required', 'Defer remains available'],
      trace: ['page: Decisions', 'decision: D-005'],
      requirements: ['Point choice recorded', 'Deferred choices continue to block handoff'],
      evidence: ['Decision D-005 status'],
      review: ['Codex handoff gating remains unresolved'],
      handoff: ['All Decision Locks must be closed before handoff can be prepared'],
    },
    {
      id: 'node-7',
      index: '07',
      label: 'Trace Evidence',
      type: 'trace',
      typeLabel: 'Evidence',
      x: 50,
      y: 82,
      status: 'draft',
      family: 'evidence',
      familyLabel: 'Evidence',
      title: 'Trace Evidence Map',
      subtitle: 'Links sources, spec fields, decisions, and artifact readiness.',
      readiness: 'needs-evidence',
      blockerCount: 2,
      evidenceCount: 4,
      description: 'Links sources, fields, decisions and artifact readiness so handoff packets remain auditable.',
      config: 'Source-target links',
      model: 'Static trace table',
      inputs: ['Included context set', 'Locked decisions'],
      outputs: ['Evidence map'],
      guardrails: ['Missing links warned', 'No export while incomplete'],
      trace: ['page: Trace & Evidence', 'table: trace links'],
      requirements: ['Each required spec field has evidence', 'Missing links stay visible'],
      evidence: ['Trace table rows', 'Missing evidence warning', 'Source-target map', 'Decision link'],
      review: ['Trace Review: missing evidence links'],
      handoff: ['Evidence map must be reviewed locally before handoff unlocks'],
    },
    {
      id: 'node-8',
      index: '08',
      label: 'Handoff Packet',
      type: 'handoff',
      typeLabel: 'Handoff',
      x: 80,
      y: 82,
      status: 'blocked',
      family: 'handoff',
      familyLabel: 'Handoff Packet',
      title: 'Static Handoff Packet',
      subtitle: 'Collects ready artifacts without writing to a repo.',
      readiness: 'blocked',
      blockerCount: 5,
      evidenceCount: 1,
      description: 'Prepares a static placeholder bundle only after specs, decisions and evidence are ready.',
      config: 'Static packet placeholder',
      model: 'No AI execution',
      inputs: ['Evidence map', 'Locked decisions'],
      outputs: ['Handoff placeholder'],
      guardrails: ['Repo writes handoff only', 'Button gated until ready'],
      trace: ['page: handoff manifest', 'gate: appState.handoffReady'],
      requirements: ['Spec validated', 'Decisions locked', 'Evidence reviewed', 'Review blockers acknowledged'],
      evidence: ['Handoff manifest placeholder'],
      review: ['Codex Handoff Review: not ready'],
      handoff: ['Prepare handoff remains disabled until all local readiness checks pass'],
    },
  ],

  nodePalette: [
    { type: 'intake', label: 'Context Node', description: 'Human goal and constraint capture', icon: 'spark' },
    { type: 'context', label: 'Context Node', description: 'Safe source selection', icon: 'branch' },
    { type: 'spec', label: 'Work Packet', description: 'Controlled spec fields', icon: 'document' },
    { type: 'review', label: 'Review Gate', description: 'Inspect-only review cards', icon: 'review' },
    { type: 'preview', label: 'Evidence', description: 'Static artifact snapshot', icon: 'eye' },
    { type: 'decision', label: 'Decision Lock', description: 'Point lock decisions', icon: 'lock' },
    { type: 'trace', label: 'Evidence', description: 'Source-to-target links', icon: 'trace' },
    { type: 'handoff', label: 'Handoff Packet', description: 'Gated static packet', icon: 'archive' },
  ],

  // Visual-only links drawn on the Workbench canvas.
  workflowEdges: [
    { source: 'node-1', target: 'node-2', tone: 'validated' },
    { source: 'node-2', target: 'node-3', tone: 'validated' },
    { source: 'node-3', target: 'node-4', tone: 'pending' },
    { source: 'node-4', target: 'node-5', tone: 'pending' },
    { source: 'node-5', target: 'node-6', tone: 'pending' },
    { source: 'node-6', target: 'node-7', tone: 'risk' },
    { source: 'node-7', target: 'node-8', tone: 'neutral' },
    { source: 'node-3', target: 'node-5', tone: 'neutral' },
  ],

  // Static architecture graph used by the golden path explainer. These nodes
  // mirror the Workbench canvas and describe mock-only artifact flow.
  architectureGraphNodes: [
    {
      id: 'arch-node-selected',
      label: 'Rough context',
      linkedNodeId: 'node-1',
      role: 'Point-provided context is captured as local, inspect-only source material.',
      output: 'Selected source context',
    },
    {
      id: 'arch-context-basket',
      label: 'Governed spec',
      linkedNodeId: 'node-3',
      role: 'The selected context is shaped into controlled spec fields and acceptance criteria.',
      output: 'Governed spec draft',
    },
    {
      id: 'arch-assistant-chat',
      label: 'Decision/evidence gate',
      linkedNodeId: 'node-6',
      role: 'D-005 keeps the handoff preview blocked until evidence, criteria, and Point lock are clear.',
      output: 'Governance checkpoint',
    },
    {
      id: 'arch-handoff-preview',
      label: 'Handoff preview',
      linkedNodeId: 'node-8',
      role: 'A static packet preview shows what would be handed off after the local gates clear.',
      output: 'Mock handoff preview',
    },
  ],

  architectureGraphEdges: [
    { source: 'arch-node-selected', target: 'arch-context-basket', label: 'Select safe context' },
    { source: 'arch-context-basket', target: 'arch-assistant-chat', label: 'Check D-005 gate' },
    { source: 'arch-assistant-chat', target: 'arch-handoff-preview', label: 'Show preview only' },
  ],

  primaryDemoPath: {
    id: 'primary-demo-path',
    name: 'rough context -> governed spec -> decision/evidence gate -> handoff preview',
    status: 'blocked',
    summary: 'Static MVP demonstration path for turning selected rough context into a governed spec and a gated handoff preview.',
    currentCheckpoint: 'D-005 Codex handoff gating',
    stages: [
      {
        id: 'rough-context',
        label: 'Rough context',
        page: 'Workbench',
        linkedNodeId: 'node-2',
        status: 'selected',
        evidenceIds: ['source-context'],
        summary: 'Selected context includes the goal brief, Context Selector, Spec Builder, and Handoff Packet nodes while protected exclusions stay sealed.',
      },
      {
        id: 'governed-spec',
        label: 'Governed spec',
        page: 'Spec Builder',
        linkedNodeId: 'node-3',
        status: 'needs-criteria',
        evidenceIds: ['source-context'],
        summary: 'Spec draft fields are visible, but acceptance criteria still block readiness until locked.',
      },
      {
        id: 'decision-evidence-gate',
        label: 'Decision/evidence gate',
        page: 'Decisions + Trace & Evidence',
        linkedNodeId: 'node-6',
        status: 'blocked',
        evidenceIds: ['locked-decision', 'validation-readiness'],
        summary: 'D-005 is the static governance checkpoint for Codex handoff readiness.',
      },
      {
        id: 'handoff-preview',
        label: 'Handoff preview',
        page: 'Preview',
        linkedNodeId: 'node-8',
        status: 'mock-preview',
        evidenceIds: ['handoff-placeholder'],
        summary: 'The handoff packet is shown as a static placeholder and never writes files or calls services.',
      },
    ],
    blockers: [
      {
        id: 'missing-acceptance-criteria',
        label: 'Acceptance criteria missing',
        status: 'open',
        blocks: 'Handoff readiness',
      },
      {
        id: 'missing-evidence',
        label: 'Required evidence missing or unreviewed',
        status: 'open',
        blocks: 'Handoff readiness',
      },
      {
        id: 'decision-lock-open',
        label: 'D-005 decision lock open',
        status: 'open',
        blocks: 'Handoff readiness',
      },
    ],
    evidenceItems: [
      {
        id: 'source-context',
        type: 'source_context',
        label: 'Source context evidence',
        sourceObjectId: 'node-2',
        targetObjectId: 'spec-draft-primary',
        status: 'attached',
        requiredForHandoff: true,
        summary: 'Selected Context is visible on Workbench and excludes runtime state, secrets, and repo write authority.',
      },
      {
        id: 'locked-decision',
        type: 'decision_lock',
        label: 'D-005 lock evidence',
        sourceObjectId: 'D-005',
        targetObjectId: 'handoff-preview',
        status: 'missing',
        requiredForHandoff: true,
        summary: 'Missing until Point locks D-005 for the static handoff preview.',
      },
      {
        id: 'validation-readiness',
        type: 'validation_result',
        label: 'Validation readiness evidence',
        sourceObjectId: 'validation-static-local',
        targetObjectId: 'handoff-preview',
        status: 'warning',
        requiredForHandoff: true,
        summary: 'Static readiness is blocked while spec fields, evidence review, or D-005 are unresolved.',
      },
      {
        id: 'handoff-placeholder',
        type: 'artifact_reference',
        label: 'Handoff placeholder evidence',
        sourceObjectId: 'apps/static-mvp/handoff/handoff-placeholder.json',
        targetObjectId: 'handoff-preview',
        status: 'attached',
        requiredForHandoff: true,
        summary: 'The placeholder exists as local mock data only and is not a produced handoff artifact.',
      },
    ],
  },

  // Initial context items included in the basket.
  contextItems: [
    {
      id: 'node-2',
      label: 'Selected context: Context Selector',
    },
    {
      id: 'node-3',
      label: 'Governed spec: Spec Builder',
    },
    {
      id: 'node-8',
      label: 'Handoff preview: Static Handoff Packet',
    },
    {
      id: 'golden-path-brief',
      label: 'Rough context: primary demo brief',
    },
  ],

  // Protected exclusions that cannot be added to AI context.
  protectedItems: [
    { id: 'runtime-state', label: 'Runtime state', status: 'excluded' },
    { id: 'secrets', label: 'Secrets', status: 'excluded' },
    { id: 'repo-write', label: 'Repo write authority', status: 'excluded' },
  ],

  assistantTranscript: [
    {
      speaker: 'user',
      text: 'Use the selected rough context to prepare a governed spec and a gated Codex handoff preview.',
    },
    {
      speaker: 'assistant',
      text: 'I can show a mock packet preview from safe context only. Runtime state, secrets, repo write authority, APIs, and external connectors remain excluded.',
    },
    {
      speaker: 'assistant',
      text: 'D-005 blocks the preview until acceptance criteria, evidence review, and the Point lock are clear in local mock state.',
    },
  ],

  handoffPacketPreview: {
    packet_id: 'OPENCLAW-HANDOFF-PREVIEW-001',
    title: 'Static MVP Primary Demo Handoff Preview',
    status: 'mock-preview',
    primary_demo_path: 'rough context -> governed spec -> decision/evidence gate -> handoff preview',
    objective: 'Align the static MVP around selected rough context becoming a governed spec and a D-005-gated handoff preview.',
    gate: {
      decision_id: 'D-005',
      name: 'Codex handoff gating',
      checkpoint: 'Static governance checkpoint before the handoff preview can be marked ready.',
      status: 'needs-lock',
    },
    allowed_paths: [
      'apps/static-mvp/**',
      'schemas/**',
      'quality/**',
      'artifacts/evidence/**',
      'docs/ops/STATUS.md',
    ],
    forbidden_actions: [
      'Add dependencies',
      'Add backend, API, auth, database, storage, or deployment',
      'Mutate runtime state',
      'Create real repo scanning or external connectors',
      'Touch secrets',
      'Modify files outside allowed paths',
    ],
    required_work: [
      'Show selected context and protected exclusions on Workbench',
      'Show governed spec fields and acceptance-criteria readiness on Spec Builder',
      'Show D-005 as the Codex handoff governance checkpoint',
      'Show context, spec, decision, validation, and placeholder evidence links',
      'Keep the handoff preview static and mock-only',
    ],
    acceptance_criteria: [
      'The user can visually follow rough context -> governed spec -> decision/evidence gate -> handoff preview',
      'D-005 is visible as the handoff gating decision',
      'Missing acceptance criteria, evidence, or decision lock visibly blocks readiness',
      'The preview remains static and mock-only',
      'Validation commands pass',
    ],
    validation_commands: ['npm run validate', 'git diff --check'],
    stop_conditions: [
      'Stop if a dependency is required',
      'Stop if backend/API/auth/database/deployment is needed',
      'Stop if real repo or external connector access is needed',
      'Stop if files outside allowed paths must change',
      'Stop if validation fails and cannot be fixed within scope',
      'Stop if a product or architecture decision is required',
    ],
    final_response_format: [
      'Verdict:',
      'Changed files:',
      'Validation output:',
      'Evidence recorded:',
      'Risks:',
      'Next recommended action:',
    ],
    selected_context: ['Selected context: Context Selector', 'Governed spec: Spec Builder', 'Handoff preview: Static Handoff Packet', 'Rough context: primary demo brief'],
    protected_exclusions: ['Runtime state', 'Secrets', 'Repo write authority'],
    included_evidence_ids: ['source-context', 'locked-decision', 'validation-readiness', 'handoff-placeholder'],
    included_decision_ids: ['D-005'],
    readiness: 'blocked',
    blocked_by: ['Acceptance criteria missing', 'D-005 needs Point lock', 'Required evidence is missing or unreviewed'],
  },

  evidenceItems: [
    {
      id: 'source-context',
      type: 'source_context',
      label: 'Source context evidence',
      sourceObjectId: 'node-2',
      targetObjectId: 'spec-draft-primary',
      status: 'attached',
      requiredForHandoff: true,
      summary: 'Selected Context is visible on Workbench and excludes runtime state, secrets, and repo write authority.',
    },
    {
      id: 'locked-decision',
      type: 'decision_lock',
      label: 'D-005 lock evidence',
      sourceObjectId: 'D-005',
      targetObjectId: 'handoff-preview',
      status: 'missing',
      requiredForHandoff: true,
      summary: 'Missing until Point locks D-005 for the static handoff preview.',
    },
    {
      id: 'validation-readiness',
      type: 'validation_result',
      label: 'Validation readiness evidence',
      sourceObjectId: 'validation-static-local',
      targetObjectId: 'handoff-preview',
      status: 'warning',
      requiredForHandoff: true,
      summary: 'Static readiness is blocked while spec fields, evidence review, or D-005 are unresolved.',
    },
    {
      id: 'handoff-placeholder',
      type: 'artifact_reference',
      label: 'Handoff placeholder evidence',
      sourceObjectId: 'apps/static-mvp/handoff/handoff-placeholder.json',
      targetObjectId: 'handoff-preview',
      status: 'attached',
      requiredForHandoff: true,
      summary: 'The placeholder exists as local mock data only and is not a produced handoff artifact.',
    },
  ],

  artifactRefs: [
    {
      id: 'artifact-static-mvp',
      type: 'static_html_app',
      status: 'needs_sync',
      label: 'COCKPIT-MVP-014 static prototype',
      linkedObjectIds: ['project-cooperative-cockpit-static-mvp', 'spec-draft-primary'],
    },
    {
      id: 'artifact-handoff-placeholder',
      type: 'handoff_placeholder',
      status: 'handoff_only',
      label: 'Static handoff placeholder',
      linkedObjectIds: ['work-packet-primary-demo', 'handoff-packet-primary-demo'],
    },
  ],

  workPacket: {
    id: 'work-packet-primary-demo',
    title: 'Static MVP Primary Demo Work Packet',
    objective: 'Align the static MVP around selected rough context becoming a governed spec and a D-005-gated handoff preview.',
    allowedPaths: ['apps/static-mvp/src/mockData.js', 'apps/static-mvp/src/state.js', 'apps/static-mvp/QA_CHECKLIST.md', 'artifacts/evidence/**'],
    forbiddenActions: [
      'Add dependencies',
      'Add backend, API, auth, database, storage, or deployment',
      'Add runtime workflow execution or real agent orchestration',
      'Add external connectors or MCP implementation',
      'Modify routing or add pages',
    ],
    acceptanceCriteria: [
      'Existing eight pages still load',
      'Existing interaction flow remains static/local',
      'Mock data exposes the locked static MVP object model entities',
      'No backend/API/auth/database/deployment/runtime behavior is introduced',
      'npm run validate passes',
    ],
    validationCommands: ['npm run validate'],
    status: 'draft',
  },

  handoffPacket: {
    id: 'handoff-packet-primary-demo',
    workPacketId: 'work-packet-primary-demo',
    readiness: 'handoff_blocked',
    blockedBy: ['acceptance-criteria', 'D-005', 'locked-decision', 'validation-readiness'],
    includedEvidenceIds: ['source-context', 'locked-decision', 'validation-readiness', 'handoff-placeholder'],
    includedDecisionIds: ['D-005'],
  },

  agentRoles: [
    {
      id: 'role-planner',
      name: 'Planner',
      purpose: 'Break bounded static MVP work into scoped tasks and acceptance checks.',
      mustNotDo: ['Add runtime orchestration', 'Expand product scope without Point lock'],
    },
    {
      id: 'role-reviewer',
      name: 'Reviewer',
      purpose: 'Inspect static artifacts, findings, decisions, and evidence without modifying runtime state.',
      mustNotDo: ['Auto-fix source files from the UI', 'Call external services'],
    },
    {
      id: 'role-qa',
      name: 'QA',
      purpose: 'Run local validation and smoke checks against the static MVP boundary.',
      mustNotDo: ['Claim tests passed without running them', 'Treat mock validation as live execution'],
    },
  ],

  // Specification fields and their statuses.
  specFields: [
    {
      id: 'objective',
      name: 'Objective',
      value: 'Align rough context to a governed spec and gated static handoff preview.',
      status: 'draft',
      suggestion: 'Keep the path static: rough context -> governed spec -> decision/evidence gate -> handoff preview.',
      evidenceIds: ['source-context'],
    },
    {
      id: 'layout-regions',
      name: 'Layout regions',
      value: 'Home summary, Workbench selected context, Spec Builder fields, Decisions gate, Trace evidence, Preview handoff placeholder',
      status: 'draft',
      suggestion: 'List the primary UI regions (header, sidebar, canvas, inspector, footer).',
      evidenceIds: ['source-context', 'handoff-placeholder'],
    },
    {
      id: 'interaction-states',
      name: 'Interaction states',
      value: 'Blocked by missing acceptance criteria, missing evidence, or open D-005 lock; ready remains mock-only.',
      status: 'draft',
      suggestion: 'Describe blocked and ready handoff readiness states.',
      evidenceIds: ['validation-readiness', 'locked-decision'],
    },
    {
      id: 'protected-surfaces',
      name: 'Protected surfaces',
      value: 'Runtime state, Secrets, Repo write authority',
      status: 'locked',
      suggestion: '',
      evidenceIds: ['source-context'],
    },
    {
      id: 'acceptance-criteria',
      name: 'Acceptance criteria',
      value: '',
      status: 'missing',
      suggestion: 'Confirm the primary path, D-005 gate, evidence links, blocked state, and static-only preview.',
      evidenceIds: [],
    },
    {
      id: 'validation-method',
      name: 'Validation method',
      value: '',
      status: 'needs-lock',
      suggestion: 'Use npm run validate plus manual static MVP navigation and no-network checks.',
      evidenceIds: ['validation-readiness'],
    },
  ],

  // Review results definitions.
  reviewResults: [
    {
      id: 'review-architecture',
      name: 'Architecture Review',
      verdict: 'Revise',
      severity: 'high',
      findings: 8,
      details: [
        'Clarify separation of concerns',
        'Define layers for context, spec, review and handoff',
        'Ensure traceability across nodes',
      ],
    },
    {
      id: 'review-security',
      name: 'Security Review',
      verdict: 'Pass with notes',
      severity: 'medium',
      findings: 3,
      details: ['No secrets in context', 'Ensure governance strip visible', 'Review agent scopes'],
    },
    {
      id: 'review-redteam',
      name: 'Red Team Review',
      verdict: '2 high‑risk ambiguities',
      severity: 'high',
      findings: 2,
      details: ['Ambiguous spec field definitions', 'Potential misuse of review actions'],
    },
    {
      id: 'review-ux',
      name: 'UX Review',
      verdict: 'Preview required',
      severity: 'low',
      findings: 1,
      details: ['UX mockup missing acceptance criteria'],
    },
    {
      id: 'review-trace',
      name: 'Trace Review',
      verdict: 'Missing evidence links',
      severity: 'medium',
      findings: 2,
      details: ['Some spec fields lack traceability to source context', 'Missing link between node and preview'],
    },
    {
      id: 'review-codex',
      name: 'Codex Handoff Review',
      verdict: 'Not ready',
      severity: 'high',
      findings: 3,
      details: ['Spec incomplete', 'Decisions unresolved', 'Preview out of sync'],
    },
  ],

  reviewRun: {
    id: 'review-run-primary-demo',
    name: 'Primary demo static review',
    status: 'review_complete',
    scopeContextIds: ['node-2', 'node-3', 'node-6', 'node-8'],
    findingIds: ['finding-spec-fields-open', 'finding-d005-open', 'finding-evidence-warning'],
    verdict: 'Not ready for handoff until static gates clear',
  },

  findings: [
    {
      id: 'finding-spec-fields-open',
      reviewRunId: 'review-run-primary-demo',
      severity: 'high',
      status: 'finding_open',
      summary: 'Spec draft remains blocked while acceptance criteria and validation method fields are unresolved.',
      recommendation: 'Keep handoff readiness blocked until required spec fields are locked in local mock state.',
      evidenceIds: ['validation-readiness'],
    },
    {
      id: 'finding-d005-open',
      reviewRunId: 'review-run-primary-demo',
      severity: 'high',
      status: 'finding_open',
      summary: 'D-005 remains the visible Point-lock gate for static handoff readiness.',
      recommendation: 'Keep D-005 in the Needs Point lock lane until the local decision is locked.',
      evidenceIds: ['locked-decision'],
    },
    {
      id: 'finding-evidence-warning',
      reviewRunId: 'review-run-primary-demo',
      severity: 'medium',
      status: 'finding_open',
      summary: 'Evidence review is incomplete for the static handoff placeholder.',
      recommendation: 'Require local evidence review before enabling mock-only handoff readiness.',
      evidenceIds: ['source-context', 'handoff-placeholder'],
    },
  ],

  // Decision definitions.
  decisions: [
    {
      id: 'D-001',
      title: 'Context Basket placement',
      description: 'Should the Context Basket be docked or floating?',
      status: 'locked',
      options: ['Floating', 'Docked', 'Collapsible'],
      selectedOption: 'Docked',
      chosenOption: 'Docked',
      requiresPointLock: false,
    },
    {
      id: 'D-002',
      title: 'Spec Builder access',
      description: 'Tab only or dedicated page?',
      status: 'locked',
      options: ['Tab', 'Page', 'Both'],
      selectedOption: 'Both',
      chosenOption: 'Both',
      requiresPointLock: false,
    },
    {
      id: 'D-003',
      title: 'Review action language',
      description: 'What wording should be used for review actions?',
      status: 'locked',
      // Avoid unsafe execution-style wording on action labels. Offer only compliant options.
      options: ['Validate', 'Start review checks'],
      selectedOption: 'Validate',
      chosenOption: 'Validate',
      requiresPointLock: false,
    },
    {
      id: 'D-004',
      title: 'Preview naming',
      description: 'Name of the preview tab/page',
      status: 'locked',
      options: ['Preview', 'UI / HTML Viewer'],
      selectedOption: 'Preview',
      chosenOption: 'Preview',
      requiresPointLock: false,
    },
    {
      id: 'D-005',
      title: 'Codex handoff gating',
      description: 'Governance checkpoint for when the static Codex handoff preview can be marked ready.',
      status: 'needs-lock',
      options: ['Gated until ready', 'Hold unavailable'],
      selectedOption: null,
      chosenOption: null,
      requiresPointLock: true,
      gates: ['handoff-preview'],
      evidenceIds: ['locked-decision', 'validation-readiness'],
    },
  ],

  // Simple trace links demonstration. Each link points from a source to a target by id.
  traceLinks: [
    { source: 'node-1', target: 'objective' },
    { source: 'node-2', target: 'layout-regions' },
    { source: 'node-2', target: 'interaction-states' },
    { source: 'source-context', target: 'objective' },
    { source: 'locked-decision', target: 'D-005' },
    { source: 'validation-readiness', target: 'validation-method' },
    { source: 'handoff-placeholder', target: 'handoff-preview' },
    { source: 'spec-field', target: 'D-005' },
  ],

  validationResults: [
    {
      id: 'validation-static-local',
      scope: 'Static MVP primary demo path',
      status: 'validation_blocked',
      command: 'npm run validate',
      summary: 'Repo validation may pass while handoff readiness remains blocked by local mock criteria.',
      evidenceRef: 'validation-readiness',
    },
    {
      id: 'validation-manual-static-mvp',
      scope: 'Manual eight-page static MVP smoke check',
      status: 'validation_warning',
      command: 'Manual browser check',
      summary: 'All eight pages must remain reachable without network/API calls before demo use.',
      evidenceRef: 'handoff-placeholder',
    },
  ],

  // Safety rules definitions for Rules & Scope page.
  rules: [
    {
      name: 'Runtime mutation',
      allowed: false,
      reviewGate: 'Blocked by default',
      notes: '',
    },
    {
      name: 'Repo writes',
      allowed: false,
      reviewGate: 'Handoff only',
      notes: '',
    },
    {
      name: 'Artifact drafting',
      allowed: true,
      reviewGate: 'Spec builder allowed',
      notes: '',
    },
    {
      name: 'Dynamic UI',
      allowed: true,
      reviewGate: 'Spec first',
      notes: '',
    },
    {
      name: 'Secrets',
      allowed: false,
      reviewGate: 'Excluded',
      notes: '',
    },
    {
      name: 'External actions',
      allowed: false,
      reviewGate: 'Blocked',
      notes: '',
    },
    {
      name: 'Review agents',
      allowed: true,
      reviewGate: 'Inspect only',
      notes: '',
    },
    {
      name: 'Codex handoff',
      allowed: true,
      reviewGate: 'Gated until ready',
      notes: '',
    },
  ],
};
